$schema: https://json-schema.org/draft-06/schema#
description: Configuration for formatting features for corpus
properties:
  fasta:
    description: Path to the reference genome fasta file
    type: string
  chromsizes:
    description: Path to the chromosome sizes file
    type: string
  blacklist:
    description: Path to the blacklist regions bed file
    type: string
  window_size:
    description: Size of the window to be used for formatting features
    type: integer
  corpus_name:
    description: Name of the corpus
    type: string
  chr_prefix:
    description: Prefix for the chromosome names
    type: string
    default: ""
  weight_col:
    description: Column to use for the weights
    type: string
  dtype:
    description: Data type of the features
    enum:
    - sbs
    - fragment-motif
    type: string
    default: sbs
  samples:
    description: Samples to be ingested
    patternProperties:
      ^[a-zA-Z0-9_]+$:
        type: string
    type: object
  features:
    description: Features to be formatted
    patternProperties:
      ^[a-zA-Z0-9_]+$:
        properties:
          processing_fn:
            description: Function to process the feature
            type: string
            default: none
          affects_windows:
            description: Whether the feature affects windows, only applicable for categorical and cardinality features
            type: boolean
            default: true
          group:
            description: Group to which the feature belongs
            type: string
            default: all
          url:
            description: URL to download the feature file
            type: array
            items:
              type: string
          type:
            description: Type of the feature
            enum:
            - bigwig
            - bedgraph
            - categorical
            - distance
            - cardinality
            - vector
            type: string
          normalization:
            description: Normalization method for the feature
            enum:
            - quantile
            - standardize
            - minmax
            - power
            type: string
            default: power
          "null":
            description: Value to replace missing values with
            type: string
            default: "."
          column:
            description: Column to use for the feature
            type: integer
            default: 4
          class_priority:
            description: Priority of the classes in the bed file
            type: array
            items:
              type: string
            default: []
        required:
        - group
        - type
        - url
        type: object
    type: object

required:
- fasta
- blacklist
- window_size
- corpus_name
- chromsizes
- weight_col
- features
- samples